export const GET_TICKET_REQUEST = "GET_TICKET_REQUEST";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";


export const POST_TICKET_REQUEST = "POST_TICKET_REQUEST";
export const POST_TICKET_SUCCESS = "POST_TICKET_SUCCESS";
export const POST_TICKET_FAILURE = "POST_TICKET_FAILURE";
