export const GET_TICKET_REQUEST = "GET_TICKET_REQUEST";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";


export const POST_TICKETS_REQUEST = "POST_TICKETS_REQUEST";
export const POST_TICKETS_SUCCESS = "POST_TICKETS_SUCCESS";
export const POST_TICKETS_FAILURE = "POST_TICKETS_FAILURE";
